stages:
  - test
  - build

test:
  stage: test
  image: golang:1.12
  script:
    - echo 127.0.0.1 quic.clemente.io >> /etc/hosts
    - go get -t ./...
    - go get github.com/golangci/golangci-lint/cmd/golangci-lint
    - golangci-lint run -E gofmt -E misspell -E goimports -D deadcode -D errcheck -D staticcheck -D gosimple -D unused --tests
    - go test -race ./...

build:
  stage: build
  image: golang:1.12
  script:
    - go get ./...
    - mkdir $CI_PROJECT_NAME-${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}
    - mv caddy $CI_PROJECT_NAME-${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}
  artifacts:
    untracked: true
    name: $CI_PROJECT_NAME-${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}
