stages:
  - test
  - build

variables:
  PKG: github.com/mholt/caddy

test:
  stage: test
  image: golang:1.12
  script:
    - echo 127.0.0.1 quic.clemente.io >> /etc/hosts
    - go get -t ./...
    - go get github.com/alecthomas/gometalinter
    - gometalinter --install
    - gometalinter --disable-all -E vet -E gofmt -E misspell -E ineffassign -E goimports -E deadcode --tests --vendor ./...
    - go test -race ./...

build:
  stage: build
  image: golang:1.12
  script:
    - cd caddy
    - go get ./...
    - go get github.com/caddyserver/builds
    - go run build.go
    - mkdir ../$CI_PROJECT_NAME-${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}
    - mv caddy ../$CI_PROJECT_NAME-${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}
  artifacts:
    untracked: true
    name: $CI_PROJECT_NAME-${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}
