stages:
  - test
  - build

test:
  stage: test
  image: golang:1.12
  script:
    - go get github.com/golangci/golangci-lint/cmd/golangci-lint
    - golangci-lint run --enable-all

build:
  stage: build
  image: golang:1.12
  script:
    - mkdir $CI_PROJECT_NAME-${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}
    - go build -o $CI_PROJECT_NAME-${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}/caddy
  artifacts:
    untracked: true
    name: $CI_PROJECT_NAME-${CI_COMMIT_TAG:-$CI_COMMIT_REF_NAME}
